export const userConstants = {
    USER_UPDATE_ALL_DATA: "USER_UPDATE_ALL_DATA",
    USER_CLEAR_DATA: "USER_CLEAR_DATA",
    UPDATE_CART_DATA: "UPDATE_CART_DATA",
    UPDATE_USER_ORDERS: "UPDATE_USER_ORDERS",
    UPDATE_USER_AUTHENTICATION_STATUS: "UPDATE_USER-AUTHENTICATION_STATUS",
}